### ISSUE TITLE
note and document

### ISSUE THREAD

**Issue by icornelius** [ZettelGeist/zettelgeist#20]
I carry over a concern I raised in #18, regarding expansion of ZettelGeist from note-taking system to writing system. The problem is that, after the deprecation of `note` and migration of the contents of that field to `document`, there is not a field dedicated exclusively to language extracted from sources. The *cordon sanitaire* between my words and my source's words is compromised:

> The move from yaml to markdown expands the versatility of ZettelGeist but will require careful thinking about the content of the `document` element. In my zetteln, the `note` element (now migrated to `document`) has always and only been a verbatim quotation from a source; the source is identified by Better BibTeX citation key and page reference in the `cite` element. My own writing has gone in the `comment` element. I think this is the right disposition for note-taking, but the current expansion of the scope of ZettelGeist changes things. 

> If I am using ZettelGeist to write modular components of an article, I want to use the `document` element for my own writing, since that is the markdown-formatted element. I'll then have some zetteln in which the `document` element is a quotation from a source and others in which the `document` element is my own prose. I'll need to keep those separate. 

I think @gkthiruvathukal is right to deprecate `note` in the new version of ZettelGeist, but I'd like to see a dedicated field for quoted language. Perhaps the field could even be a child of `cite`, like so: 

```
cite:
  bibkey:
  page:
  quote:
```

Users who, like me, have used the `note` field to record quoted language will then want to migrate the content of that field to `quote`, not `document`. This will free up the new markdown `document` element for own writing.

**Comment by gkthiruvathukal** [comment]
@icornelius Based on our e-mail discussion, we have decided that `note` will be retained for its original purpose.  @dbdennis and I also think there is no good reason to deprecate `note` after all.

The Markdown payload will just be treated entirely as a new property, `document`, and exclusively for writing purposes. `document` should not be used in the YAML header, and `note` is still fully supported. I see no reason not to support both as ZettelGeist can pretty much be expanded at will to include new fields.

If you agree with me, I think I'm going to mark this as closed, pending your follow-up. I actually could be talked into adding an optional `quote` to the `cite` block. But since we plan to retain `note`, do you see this as a necessary addition?

**Comment by icornelius** [comment]
@gkthiruvathukal I support this solution. If `note` is retained I don't see `quote` as a necessary addition. Thanks!

**Comment by gkthiruvathukal** [comment]
Thanks, @icornelius! I will close this out then.
